package com.smartamenities.data.model

// ─────────────────────────────────────────────────────────────────────────────
// Core domain models for the Smart Amenities Assistance System
// These data classes are shared between the UI, ViewModel, and Repository layers
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Represents a single amenity inside Terminal D (restroom, lactation room, etc.)
 *
 * Every field maps directly to a requirement in the SRS:
 *  - status         → FR 3.1 / FR 3.4 (real-time or fallback status)
 *  - crowdLevel     → FR 2.3 (factor into route scoring)
 *  - estimatedWalkMinutes → FR 1.1.4, FR 1.2.4 (rank by time-to-reach)
 *  - isWheelchairAccessible → FR 4.3 (accessibility filtering)
 *  - dataFreshnessTimestamp → FR 3.3 (show last-updated time in UI)
 */
data class Amenity(
    val id: String,
    val name: String,
    val type: AmenityType,
    val floor: Int,                         // Terminal D floor number (1 or 2)
    val locationX: Float,                   // Normalized map coordinate (0.0–1.0)
    val locationY: Float,
    val status: AmenityStatus,
    val crowdLevel: CrowdLevel,
    val estimatedWalkMinutes: Int,          // Time-to-reach from passenger's current position
    val isWheelchairAccessible: Boolean,
    val isStepFreeRoute: Boolean,           // Route to this amenity has no stairs/escalators
    val isFamilyRestroom: Boolean,
    val isGenderNeutral: Boolean,
    val dataFreshnessTimestamp: Long,       // Unix millis of last status update
    val confidenceScore: Float,             // 0.0–1.0; reflects data source reliability
    val gateProximity: String               // e.g. "Near Gate D30" for quick orientation
)

/** Which type of amenity this is — used for filtering in the list view (FR 1.2.2) */
enum class AmenityType(val displayName: String, val iconDescription: String) {
    RESTROOM("Restroom", "Restroom icon"),
    FAMILY_RESTROOM("Family Restroom", "Family restroom icon"),
    LACTATION_ROOM("Lactation Room", "Lactation room icon"),
    GENDER_NEUTRAL_RESTROOM("Gender-Neutral Restroom", "Gender-neutral icon"),
    WATER_FOUNTAIN("Water Fountain", "Water fountain icon")
}

/** Real-time open/closed/unknown state — FR 3.1, FR 3.4 */
enum class AmenityStatus(val displayName: String) {
    OPEN("Open"),
    CLOSED("Closed"),
    OUT_OF_SERVICE("Out of Service"),
    UNKNOWN("Status Unknown")              // Shown when real-time data is unavailable
}

/**
 * Crowd level label derived from sensor or simulated occupancy data — FR 2.3
 * Matches the 3-tier label system in the High-Level Architecture (CrowdLevelCalculator)
 */
enum class CrowdLevel(val displayName: String, val waitEstimateMinutes: Int) {
    EMPTY("Empty", 0),
    SHORT("Short Wait", 0),
    MEDIUM("Medium Wait", 5),
    LONG("Long Wait", 10),
    UNKNOWN("Unknown", 0)
}

enum class SimulationLocation(val displayName: String) {
    TERMINAL_D_ALL("All Zones"),
    TERMINAL_D_EAST("East Zone  (Gates D5 – D18)"),
    TERMINAL_D_CENTRAL("Central Zone  (Gates D19 – D30)"),
    TERMINAL_D_WEST("West Zone  (Gates D31 – D40)")
}

enum class SimulationPreset(val displayName: String) {
    HIGH_TRAFFIC("High Traffic"),
    LOW_TRAFFIC("Low Traffic"),
    PEAK_HOURS("Peak Hours")
}

data class SimulationConfig(
    val selectedLocation: SimulationLocation = SimulationLocation.TERMINAL_D_ALL,
    val gateCount: Int = 18,
    val crowdLevel: Int = 2,
    val averageUsageTimeMinutes: Int = 6,
    val isSystemOpen: Boolean = true,
    val isSimulationModeEnabled: Boolean = false
)

data class AmenitySimulationOverride(
    val status: AmenityStatus? = null,
    val crowdLevel: CrowdLevel? = null
)

data class AdminSimulationState(
    val config: SimulationConfig = SimulationConfig(),
    val amenities: List<Amenity> = emptyList(),
    val overrides: Map<String, AmenitySimulationOverride> = emptyMap()
)

// ─────────────────────────────────────────────────────────────────────────────
// Navigation models
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A complete route from the passenger's current position to a selected amenity.
 * Generated by RouteCalculator (Dijkstra's algorithm per HLA doc).
 */
data class Route(
    val amenityId: String,
    val steps: List<NavigationStep>,
    val totalWalkMinutes: Int,
    val totalWaitMinutes: Int,              // Crowd wait added on top of walk time
    val isStepFreeRoute: Boolean,
    val computedAtTimestamp: Long           // Used to detect stale cached routes
)

/**
 * One instruction in a turn-by-turn navigation sequence — FR 2.2.1
 * Displayed graphically, textually, and (in a future iteration) audibly
 */
data class NavigationStep(
    val stepNumber: Int,
    val instruction: String,               // e.g. "Turn left at Gate D22"
    val directionIcon: DirectionIcon,
    val distanceMeters: Float,
    val floorTransition: FloorTransition?  // Non-null when the step involves level change
)

enum class DirectionIcon {
    STRAIGHT, TURN_LEFT, TURN_RIGHT, SLIGHT_LEFT, SLIGHT_RIGHT,
    ELEVATOR_UP, ELEVATOR_DOWN, ESCALATOR_UP, ESCALATOR_DOWN,
    STAIRS_UP, STAIRS_DOWN, ARRIVE
}

/** Describes a floor transition step — used to ensure accessibility constraints (FR 2.7) */
data class FloorTransition(
    val fromFloor: Int,
    val toFloor: Int,
    val transitionType: TransitionType
)

enum class TransitionType { ELEVATOR, ESCALATOR, STAIRS }

// ─────────────────────────────────────────────────────────────────────────────
// User preference models — FR 4.1, FR 4.2, NFR 4.1
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Stored locally on device — no PII, only accessibility flags (NFR 4.1)
 * Passed to RouteCalculator and AmenityRankingEngine to personalise results
 */
data class UserPreferences(
    val requiresWheelchairAccess: Boolean = false,
    val requiresStepFreeRoute: Boolean = false,
    val preferFamilyRestroom: Boolean = false,
    val preferGenderNeutral: Boolean = false,
    val preferredAmenityType: AmenityType = AmenityType.RESTROOM
)
